import { StreamElementsEvent } from "nodecg-io-streamelements/extension/StreamElementsEvent";

declare module Alerts {
  interface Alert {
    name?: string;
    message: string;
    attachMsg?: string;
    duration?: number;
    media?: string[] | number[];
    sound?: string;
    layout?: string;
    volume?: number;
    keywordColour?: string;
    fontColour?: string;
    customCSS?: string;
    font?: string;
    fontWeight?: string;
    fontSize?: string;
    alert?: number;
    event?: StreamElementsEvent["data"];
  }
  interface Asset {
    // Generated by https://quicktype.io
    base: string;
    namespace: string;
    category: string;
    ext: string;
    name: string;
    sum: string;
    url: string;
  }
  interface ActivateAlert {
    attachedMsg?: string;
    activate?: boolean;
    message?: string;
    alert?: number;
    event?: any;
  }
}

export type AlertType = StreamElementsEvent["type"];
