declare module Alerts {
  interface Alert {
    name?: string
    message: string
    attachedMessage?: string | null
    duration?: number
    media?: string
    sound?: string
    layout?: string
    volume?: string
    keywordColour?: string
    fontColour?: string
    customCSS?: string
    font?: string
    fontWeight?: string
    fontSize?: string
    alert?: number
  }
  interface Asset {
    // Generated by https://quicktype.io
    base: string
    namespace: string
    category: string
    ext: string
    name: string
    sum: string
    url: string
  }
  interface ActivateAlert {
    activate: boolean
    message: string
    alert: number
  }
}
